"""walt/kernel/toys.py — tiny endgame subgames with enumerable exact values.

Toy roots are generated by the zeb engine itself under seeded RANDOM play
(no nets anywhere), so every play_history / team_points / current_trick is
consistent by construction; the hidden-world sets are hand-picked determinstic
subsets of the physics-exact enumeration (walt.worlds), with deliberately
non-uniform weights to catch normalization bugs. The registry covers 1-trick
and 2-trick roots, 7 decl_ids, hero declaring and defending, and world counts
1 / 3 / 12.

Exact values come from explicit enumeration: `discover_free_infosets` walks
the full support tree, `pure_profiles` enumerates ALL pure info-set
strategies of the free seats, `joint_value_matrix` prices every joint pure
profile with reference.profile_value, and `zero_sum_value` solves the
resulting matrix game exactly (LP) when the two free seats are on opposite
teams. On the same team, the exact value is the matrix max (a common-payoff
game against a pinned environment attains its optimum at a pure profile).
"""
from __future__ import annotations

import itertools
import random
from dataclasses import dataclass

import numpy as np
from scipy.optimize import linprog

from walt.contracts import EndgameRoot
from walt.kernel import reference as ref
from walt.worlds import enumerate_worlds

__all__ = [
    "Toy",
    "all_toys",
    "get_toy",
    "payoff_points",
    "payoff_make",
    "gen_engine_root",
    "discover_free_infosets",
    "lowest_legal_sigma",
    "pure_profiles",
    "joint_value_matrix",
    "zero_sum_value",
]


def payoff_points() -> np.ndarray:
    """E[declaring points] leaf table."""
    return np.arange(43, dtype=np.float64)


def payoff_make(bid_value: int) -> np.ndarray:
    """P(make) leaf table: step at the bid line, declaring orientation."""
    return (np.arange(43) >= int(bid_value)).astype(np.float64)


# --------------------------------------------------------------------------- #
#  Engine-generated roots (consistent by construction)                         #
# --------------------------------------------------------------------------- #

def gen_engine_root(seed: int, tricks: int) -> tuple:
    """Random-play prefix to a trick boundary with `tricks` tiles per seat;
    hero = the leader there. Returns (root, worlds) — worlds is the FULL
    physics-exact enumeration. Deterministic in (seed, tricks)."""
    from forge.zeb.game import (
        apply_action, current_player, legal_actions, new_game,
    )
    st = new_game(seed)
    rng = random.Random((seed << 4) ^ tricks)
    target = 7 - tricks
    while not (len(st.play_history) == target * 4 and not st.current_trick):
        st = apply_action(st, rng.choice(legal_actions(st)))
    me = current_player(st)
    rem = tuple(sorted(d for d in st.hands[me] if d not in st.played))
    root = EndgameRoot(
        decl_id=st.decl_id, bidder=st.bidder, bid_value=st.bid_state.high_bid,
        bids=st.bid_state.bids, dealer=st.dealer, me=me, my_hand=rem,
        play_history=st.play_history, trick_leader=st.trick_leader,
        current_trick=st.current_trick, team_points=st.team_points,
    )
    worlds = enumerate_worlds(root)
    if worlds.shape[0] == 0:
        raise ValueError(f"seed {seed}: no consistent worlds")
    return root, worlds


@dataclass(frozen=True)
class Toy:
    name: str
    root: EndgameRoot
    worlds: np.ndarray   # (N, 3) uint32, hand-picked subset
    weights: np.ndarray  # (N,) float64, non-uniform on purpose
    tricks: int

    @property
    def hero_declaring(self) -> bool:
        return self.root.me % 2 == self.root.bidder % 2

    def build(self, impl=ref):
        return impl.build_subgame(self.root, self.worlds, self.weights)


# (name, engine seed, tricks, n_worlds). Seeds were searched once
# (scratch/cfr/find_toys.py) and are frozen here; regeneration is exact.
_SPECS = (
    ("t1_decl_w3",  3,  1, 3),    # decl 6, hero declaring
    ("t1_def_w1",   4,  1, 1),    # decl 3, hero defending
    ("t2_decl_w1",  6,  2, 1),    # decl 3, hero declaring
    ("t2_decl_w3",  23, 2, 3),    # decl 5, hero declaring
    ("t2_decl_w12", 8,  2, 12),   # decl 1, hero declaring
    ("t2_def_w1",   41, 2, 1),    # decl 0, hero defending
    ("t2_def_w3",   34, 2, 3),    # decl 2, hero defending
    ("t2_def_w12",  20, 2, 12),   # decl 4, hero defending
)

_CACHE: dict = {}


def get_toy(name: str) -> Toy:
    if name in _CACHE:
        return _CACHE[name]
    spec = {s[0]: s for s in _SPECS}.get(name)
    if spec is None:
        raise KeyError(f"unknown toy {name!r}; have {[s[0] for s in _SPECS]}")
    _, seed, tricks, n = spec
    root, worlds = gen_engine_root(seed, tricks)
    if worlds.shape[0] < n:
        raise ValueError(f"toy {name}: only {worlds.shape[0]} worlds, need {n}")
    idx = np.unique(np.linspace(0, worlds.shape[0] - 1, n).round().astype(int))
    assert len(idx) == n
    toy = Toy(name=name, root=root, worlds=worlds[idx],
              weights=np.arange(1, n + 1, dtype=np.float64), tricks=tricks)
    _CACHE[name] = toy
    return toy


def all_toys() -> list:
    return [get_toy(s[0]) for s in _SPECS]


# --------------------------------------------------------------------------- #
#  Support-tree exploration                                                    #
# --------------------------------------------------------------------------- #

def _explore(sub, expand) -> None:
    """Walk the public support tree. `expand(seat, hand, node, legal)` returns
    the moves to branch on for that info set; worlds merge per public child.
    Same node/merge discipline as reference.br_solve, minus values."""
    from walt.tables import get_luts
    luts = get_luts(sub.decl_id)

    def walk(p, pub, node, wcur, my_mask):
        if p == 28:
            return
        actor = (pub.leader + pub.n_in_trick) % 4
        if actor == sub.me:
            hands = np.full(wcur.shape[0], my_mask, dtype=np.int64)
        else:
            hands = wcur[:, sub.col_of[actor]]
        child: dict = {}
        for h in np.unique(hands):
            sel = np.flatnonzero(hands == h)
            legal = ref.legal_tiles(int(h), pub.led_tile, sub.decl_id)
            for m in expand(actor, int(h), node, legal):
                if m not in legal:
                    raise ValueError(f"expand returned illegal move {m}")
                child.setdefault(int(m), []).append(sel)
        for m in sorted(child):
            sel = np.concatenate(child[m])
            w2 = wcur[sel]
            my2 = my_mask
            if actor == sub.me:
                my2 = my_mask & ~(1 << m)
            else:
                w2 = w2.copy()
                w2[:, sub.col_of[actor]] &= ~(1 << m)
            walk(p + 1, ref._pub_step(pub, actor, m, luts, sub.bid_team),
                 node + (m,), w2, my2)

    walk(sub.p0, sub.pub0, (), sub.worlds, sub.my_mask0)


def lowest_legal_sigma(sub, pinned_seats) -> ref.SigmaTable:
    """A known deterministic profile: pinned seats always play their lowest
    legal domino. Covers every info set reachable while the OTHER seats play
    anything legal (full-width), so it is a valid pin for cfr_solve."""
    pinned_seats = set(int(s) for s in pinned_seats)
    sig = ref.SigmaTable()

    def expand(seat, hand, node, legal):
        if seat in pinned_seats:
            sig.set(seat, hand, node, legal[0])
            return (legal[0],)
        return legal

    _explore(sub, expand)
    return sig


def discover_free_infosets(sub, free_seats, pinned: dict) -> dict:
    """All info sets of the free seats reachable while pinned seats follow
    their profiles: {(seat, hand, node): legal moves tuple}, insertion-ordered
    by first reach."""
    free_seats = set(int(s) for s in free_seats)
    isets: dict = {}

    def expand(seat, hand, node, legal):
        if seat in free_seats:
            isets.setdefault((seat, hand, node), legal)
            return legal
        moves, probs = pinned[seat].dist(seat, hand, node)
        return tuple(m for m, pr in zip(moves, probs) if pr > 0.0)

    _explore(sub, expand)
    return isets


# --------------------------------------------------------------------------- #
#  Pure-profile enumeration + exact values                                     #
# --------------------------------------------------------------------------- #

def pure_profiles(isets: dict, seat: int) -> list:
    """ALL pure info-set strategies of `seat` (as SigmaTables) over its
    entries in `isets`."""
    keys = [k for k in isets if k[0] == seat]
    choice_lists = [isets[k] for k in keys]
    out = []
    for combo in itertools.product(*choice_lists):
        sig = ref.SigmaTable()
        for (s, h, node), m in zip(keys, combo):
            sig.set(s, h, node, m)
        out.append(sig)
    return out


def joint_value_matrix(sub, payoff43, seat_u, pures_u, seat_v, pures_v,
                       pinned: dict) -> np.ndarray:
    """M[i, j] = declaring-orientation value when seat_u plays pures_u[i],
    seat_v plays pures_v[j], all other seats follow `pinned`."""
    M = np.empty((len(pures_u), len(pures_v)), dtype=np.float64)
    for i, pu in enumerate(pures_u):
        for j, pv in enumerate(pures_v):
            profiles = dict(pinned)
            profiles[seat_u] = pu
            profiles[seat_v] = pv
            M[i, j] = ref.profile_value(sub, profiles, payoff43)
    return M


def zero_sum_value(M: np.ndarray, sign_u: float) -> float:
    """Exact mixed value of the matrix game (row player maximizes
    sign_u * declaring value; column player the negative). Returns the value
    in DECLARING orientation."""
    A = sign_u * np.asarray(M, dtype=np.float64)   # row player's utility
    n, m = A.shape
    # variables: x (n row probs), v. maximize v s.t. A^T x >= v.
    c = np.zeros(n + 1)
    c[-1] = -1.0
    A_ub = np.hstack([-A.T, np.ones((m, 1))])      # v - (A^T x)_j <= 0
    b_ub = np.zeros(m)
    A_eq = np.zeros((1, n + 1))
    A_eq[0, :n] = 1.0
    b_eq = np.array([1.0])
    bounds = [(0.0, None)] * n + [(None, None)]
    res = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq,
                  bounds=bounds, method="highs")
    if not res.success:
        raise RuntimeError(f"matrix game LP failed: {res.message}")
    return float(sign_u * res.x[-1])
