"""Summarize exposure_scan_a_rows.jsonl into exposure_scan_a.md."""

from __future__ import annotations

import json
import statistics
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROWS = HERE / "exposure_scan_a_rows.jsonl"
MD = HERE / "exposure_scan_a.md"

DEPTHS = (16, 18, 20, 22)
SEED_START = 900000


def quantiles(values: list[float], qs=(0.5, 0.9, 0.99, 1.0)) -> dict[str, float]:
    if not values:
        return {f"q{int(q*100)}": 0.0 for q in qs}
    s = sorted(values)
    out = {}
    for q in qs:
        if q >= 1.0:
            out[f"q{int(q*100)}"] = s[-1]
        else:
            idx = min(len(s) - 1, int(q * len(s)))
            out[f"q{int(q*100)}"] = s[idx]
    return out


def histogram(values: list[float], edges) -> list[tuple[str, int]]:
    bins = [0] * (len(edges) - 1)
    for v in values:
        for i in range(len(edges) - 1):
            if edges[i] <= v < edges[i + 1] or (i == len(edges) - 2 and v == edges[-1]):
                bins[i] += 1
                break
    return [(f"[{edges[i]:.2f},{edges[i+1]:.2f})", bins[i]) for i in range(len(edges) - 1)]


def main() -> int:
    rows = [json.loads(l) for l in ROWS.read_text().splitlines() if l.strip()]
    n = len(rows)
    scanned = [r for r in rows if not r.get("skipped")]
    skipped = [r for r in rows if r.get("skipped")]
    n_scanned = len(scanned)
    seeds = sorted({r["deal_seed"] for r in rows})

    de = [r.get("dead_end_mass", 0.0) for r in scanned]
    iv = [r.get("invalid_mass", 0.0) for r in scanned]
    nz_de = [r for r in scanned if r.get("dead_end_mass", 0.0) > 0.0]
    nz_iv = [r for r in scanned if r.get("invalid_mass", 0.0) > 0.0]
    nz_de_vals = [r["dead_end_mass"] for r in nz_de]
    nz_iv_vals = [r["invalid_mass"] for r in nz_iv]

    frac_de = len(nz_de) / n_scanned if n_scanned else 0.0
    frac_iv = len(nz_iv) / n_scanned if n_scanned else 0.0

    # Per-depth breakdown.
    by_depth = {}
    for d in sorted({r["depth"] for r in scanned}):
        sub = [r for r in scanned if r["depth"] == d]
        sub_de = [r for r in sub if r.get("dead_end_mass", 0.0) > 0.0]
        sub_iv = [r for r in sub if r.get("invalid_mass", 0.0) > 0.0]
        by_depth[d] = (len(sub), len(sub_de), len(sub_iv),
                       statistics.mean([r["exact_world_count"] for r in sub]) if sub else 0)

    worst = sorted(scanned, key=lambda r: -(r.get("invalid_mass", 0.0) + r.get("dead_end_mass", 0.0)))[:10]

    hist_edges = [0.0, 0.05, 0.1, 0.2, 0.34, 0.5, 0.6667, 0.8, 1.0001]
    de_hist = histogram(nz_de_vals, hist_edges)
    iv_hist = histogram(nz_iv_vals, hist_edges)
    de_q = quantiles(nz_de_vals)
    iv_q = quantiles(nz_iv_vals)

    L = []
    A = L.append
    A("# Stage 0 exposure Scan A: legacy-MRV malformed-mass state scan")
    A("")
    A("## Population definition")
    A("")
    A("**This is a RECONSTRUCTED PROXY population, not the literal historical "
      "decision stream.** States are generated by uniform random *legal* playouts, "
      "exactly the audit's `advance_fixture` construction "
      "(`new_game(seed, skip_bidding=True)` then `random.Random(deal_seed)` choosing "
      "legal slots), generalized to snapshot at several play depths along one rollout "
      "per deal seed.")
    A("")
    A(f"- deal seeds: {len(seeds)} consecutive seeds from {SEED_START} "
      f"(includes the historical audit seed 900013).")
    A(f"- rollout_seed == deal_seed (one random legal playout per seed).")
    A(f"- snapshot depths (plays into the hand): {sorted({r['depth'] for r in rows})} "
      f"-- trick 4-6 territory, pool small, enumeration tractable.")
    A(f"- each seed yields one decision state per depth (current player about to act).")
    A("")
    A("Per state, the analytic legacy-MRV emulator "
      "(`audit.analytic_mrv_distribution`, no sampling, no oracle) gives the exact "
      "`dead_end_mass` (probability the legacy greedy recursion hit a no-candidate "
      "seat and injected domino 0) and `invalid_mass` (analytic MRV mass on worlds "
      "outside the exact public-consistent set). Exact world set from "
      "`enumerate_worlds_cpu`.")
    A("")
    A("Alternative denominators (future Scan A variants -- different, more faithful "
      "populations):")
    A("")
    A("- **forge E[Q] generation seeds** -- the actual deal/state seeds the Stage-1 "
      "/ E[Q] training corpus was generated from; measures corpus exposure directly.")
    A("- **arena result states** -- the decision states that occurred in recorded "
      "arena / champion matches; measures match-outcome exposure directly.")
    A("")
    A("Both are the true historical decision streams; the random-playout proxy here "
      "is a tractable stand-in that shares the late-game structural regime but not "
      "the exact state visitation distribution.")
    A("")
    A("## Results")
    A("")
    A(f"- N states scanned: **{n_scanned}**")
    A(f"- N skipped (intractable, exposure-unknown): **{len(skipped)}** "
      f"(tractability gate: `should_enumerate(depth, threshold=100000)` + exact "
      f"post-enumeration guard)")
    A(f"- fraction with `dead_end_mass > 0`: **{frac_de:.4%}** "
      f"({len(nz_de)}/{n_scanned})")
    A(f"- fraction with `invalid_mass > 0`: **{frac_iv:.4%}** "
      f"({len(nz_iv)}/{n_scanned})")
    A(f"- mean `dead_end_mass` over all scanned: {statistics.mean(de):.6f}; "
      f"over nonzero: {statistics.mean(nz_de_vals) if nz_de_vals else 0:.6f}")
    A(f"- mean `invalid_mass` over all scanned: {statistics.mean(iv):.6f}; "
      f"over nonzero: {statistics.mean(nz_iv_vals) if nz_iv_vals else 0:.6f}")
    A("")
    A("In this emulator every nonzero state has `dead_end_mass == invalid_mass` "
      "(the domino-0 injection is exactly the malformed mass), so the two fractions "
      "coincide.")
    A("")
    A("### Per-depth breakdown")
    A("")
    A("| depth | scanned | nz dead_end | nz invalid | mean exact worlds |")
    A("|---:|---:|---:|---:|---:|")
    for d, (ns, nde, niv, mw) in sorted(by_depth.items()):
        A(f"| {d} | {ns} | {nde} | {niv} | {mw:.1f} |")
    A("")
    A("### Nonzero-mass quantiles")
    A("")
    A(f"- dead_end_mass (nonzero, N={len(nz_de_vals)}): "
      f"median {de_q['q50']:.4f}, p90 {de_q['q90']:.4f}, p99 {de_q['q99']:.4f}, "
      f"max {de_q['q100']:.4f}")
    A(f"- invalid_mass (nonzero, N={len(nz_iv_vals)}): "
      f"median {iv_q['q50']:.4f}, p90 {iv_q['q90']:.4f}, p99 {iv_q['q99']:.4f}, "
      f"max {iv_q['q100']:.4f}")
    A("")
    A("### Histogram of nonzero dead_end_mass")
    A("")
    A("| bin | count |")
    A("|---|---:|")
    for label, c in de_hist:
        A(f"| {label} | {c} |")
    A("")
    A("### Histogram of nonzero invalid_mass")
    A("")
    A("| bin | count |")
    A("|---|---:|")
    for label, c in iv_hist:
        A(f"| {label} | {c} |")
    A("")
    A("### Worst 10 states by malformed mass")
    A("")
    A("| seed | depth | dead_end | invalid | exact worlds | pool | hand_sizes | voids |")
    A("|---|---:|---:|---:|---:|---:|---|---|")
    for r in worst:
        A(f"| {r['deal_seed']} | {r['depth']} | "
          f"{r.get('dead_end_mass',0.0):.4f} | {r.get('invalid_mass',0.0):.4f} | "
          f"{r.get('exact_world_count','-')} | {r.get('pool_size','-')} | "
          f"{r.get('hand_sizes','-')} | {r.get('void_counts','-')} |")
    A("")
    A("## Interpretation")
    A("")
    A(f"On this proxy population, roughly **{frac_de:.2%}** of tractable late-game "
      "decision states carried nonzero legacy malformed mass. The historical audit "
      "seed 900013 at play 20 reproduces exactly: dead_end = invalid = 1/3, 12 exact "
      "worlds, pool `{20,22,31,32,44,63}`. Nonzero mass concentrates in states with "
      "tight void constraints and small pools (a void seat whose only legal "
      "candidates get consumed, forcing the greedy recursion into a no-candidate "
      "branch). This scan measures **distributional exposure only** -- whether a "
      "state *could* draw a malformed world. It does NOT establish decision harm; "
      "that is Scan B (argmax flip / regret under the oracle), which runs later on "
      "MPS over exactly these nonzero-mass states.")
    A("")
    A("Skipped (intractable) states are counted as exposure-unknown, not as "
      "zero-exposure.")

    MD.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"Wrote {MD}")
    print(f"scanned={n_scanned} skipped={len(skipped)} nz_de={len(nz_de)} "
          f"nz_iv={len(nz_iv)} frac_de={frac_de:.4%}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
